root: true

env:
  node: true
  es6: true

extends:
  - eslint:all
  - plugin:vue/recommended
  # - plugin:prettier/recommended
  - prettier
  # - prettier/@typescript-eslint
  - prettier/vue

plugins:
  - prettier
  - vue

rules:
  no-console: "off"

  no-debugger: "off"

  arrow-parens:
    - error
    - as-needed
  comma-dangle:
    - error
    - never

  complexity:
    - warn
    - max: 25

  capitalized-comments:
    - off

  curly:
    - error
    - multi

  global-require:
    - off

  id-length:
    - error
    - min: 2
      exceptions:
        - e
        - h
        - i
        - x
        - y

  implicit-arrow-linebreak:
    - off

  indent:
    - off
    - 2
    - ignoredNodes:
        - ConditionalExpression

  init-declarations:
    - off

  function-call-argument-newline:
    - error
    - consistent

  line-comment-position:
    - off

  max-statements:
    - warn
    - 25

  nonblock-statement-body-position:
    - error
    - any

  no-inline-comments:
    - off

  no-magic-numbers:
    - off

  no-nested-ternary:
    - off

  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-sync:
    - off

  no-ternary:
    - off

  no-undefined:
    - off

  no-warning-comments:
    - warn

  object-curly-spacing:
    - off

  one-var:
    - error
    - never

  padded-blocks:
    - error
    - never

  prefer-named-capture-group:
    - off

  quotes:
    - error
    - single

  radix:
    - error
    - as-needed

  sort-keys:
    - off

  strict:
    - off

  vue/require-default-prop:
    - warn

  vue/html-self-closing:
    - error
    - html:
        void: always

  vue/max-attributes-per-line:
    - error
    - singleline: 5

  vue/no-v-html:
    - off
