language: node_js
node_js:
  - lts/*
install:
  - npm ci
  - npm run lerna:bootstrap
jobs:
  include:
    # 测试 shared-utils
    - stage: test-shared-utils
      name: "Test shared utils"
      script:
        - cd packages/shared-utils
        - npm run test

    # 测试并部署 DEMO
    - stage: demo
      name: "Test and Deploy Demo"
      script:
        - cd packages/theme
        - npm run copy-demo
        - npm run build-demo
      before_deploy: echo theme-demo.mrhope.site >> tests/demo-dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: packages/theme/tests/demo-dist
        github-token: $Github_Token
        repo: Mister-Hope/theme-demo
        on:
          all_branches: true

    # 测试文档
    - stage: test-docs
      name: "Test Offical Docs"
      script: 
        - cd packages/theme
        - npm run copy-docs
        - npm run build-docs
      before_deploy: echo vuepress-theme-beta.mrhope.site >> dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: packages/theme/dist
        github-token: $Github_Token
        repo: Mister-Hope/vuepress-theme-hope-docs-beta
        on:
          all_branches: true

    # 部署文档
    - stage: deploy-docs
      name: "Deploy Offical Docs"
      script: 
        - cd packages/theme
        - npm run copy-docs
        - npm run build-docs
      before_deploy: echo vuepress-theme.mrhope.site >> dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: packages/theme/dist
        github-token: $Github_Token

stages:
  - name: test-shared-utils
  - name: demo
  - name: test-docs
    if: branch != master
  - name: deploy-docs
    if: branch = master
