language: node_js
node_js:
  - lts/*
install:
  - yarn install
  - yarn run lerna:bootstrap
jobs:
  include:
    # 测试 shared-utils
    - stage: test-shared-utils
      name: "Test shared utils"
      script:
        - yarn run share-utils:test

    # 测试并部署 DEMO
    - stage: test-theme
      name: "Test and Deploy Theme-test"
      script:
        - yarn run theme-test:build
      before_deploy: echo theme-demo.mrhope.site >> tests/dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: tests/dist
        github-token: $Github_Token
        repo: Mister-Hope/theme-demo
        on:
          all_branches: true

    # 部署评论文档
    - stage: comment-docs
      name: "Deploy Comment Docs"
      script:
        - yarn run comment-docs:build
      before_deploy: echo comment.mrhope.site >> docs/comment/dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/comment/dist
        github-token: $Github_Token
        repo: Mister-Hope/vuepress-plugin-comment-docs

    # 部署Markdown增强文档
    - stage: md-enhance-docs
      name: "Deploy Markdown Enhance Docs"
      script:
        - yarn run md-enhance-docs:build
      before_deploy: echo vuepress-md.mrhope.site >> docs/md-enhance/dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/md-enhance/dist
        github-token: $Github_Token
        repo: Mister-Hope/vuepress-plugin-md-enhance-docs

    # 部署文档
    - stage: deploy-docs
      name: "Deploy Offical Docs"
      script:
        - yarn run theme:build
      before_deploy: echo vuepress-theme.mrhope.site >> docs/theme/dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/theme/dist
        github-token: $Github_Token

stages:
  - name: test-shared-utils
  - name: demo
  - name: comment-docs
    if: branch = master
  - name: md-enhance-docs
    if: branch = master
  - name: deploy-docs
    if: branch = master
